Beneficiarios/urls.py
from django.urls import path

from Beneficiarios.views import *

app_name = 'Beneficiarios'

urlpatterns = [
    path('<int:id_jornada>/beneficiarios/registrar', BeneficiariosNew.as_view(),
         name='beneficiarios_create'),
    path('beneficiarios/<int:id>/antecedentes/registrar', AntecedentesNew.as_view(),
         name='antecedentes_create'),
    path('beneficiarios', BeneficiariosList.as_view(), name='beneficiarios'),
    path('beneficiarios_json', BeneficiariosListJson.as_view(),
         name='beneficiarios_json'),
    path('beneficiarios/<int:pk>',
         BeneficiariosDetailView.as_view(), name='beneficiario'),
    path('beneficiarios/<int:pk>/expediente',
         BeneficiariosRecordView.as_view(), name='beneficiario_record'),
    path('r_est/<int:pk>',
         rEstJSON.as_view(), name='rEst'),
    path('r_tam/<int:pk>',
         rTamJSON.as_view(), name='rTam'),
    path('r_qui/<int:pk>',
         rQuiJSON.as_view(), name='rQui'),
    path('r_mic/<int:pk>',
         rMicJSON.as_view(), name='rMic'),
    path('r_hem/<int:pk>',
         rHemJSON.as_view(), name='rHem'),
    path('r_glu/<int:pk>',
         rGluJSON.as_view(), name='rGlu'),
    path('r_con/<int:pk>',
         rConJSON.as_view(), name='rCon'),
    path('r_adh/<int:pk>',
         rAdhJSON.as_view(), name='rAdh'),
    path('r_ham/<int:pk>',
         rHamJSON.as_view(), name='rHam'),
    path('r_mal/<int:pk>',
         rMalJSON.as_view(), name='rMal'),
    path('r_reg/<int:pk>',
         rRegJSON.as_view(), name='rReg'),


         
]

Doctores/urls.py
from django.urls import path, include
from .views import *

app_name = 'Doctores'

urlpatterns = [
    path('capacitaciones', ReportesView.as_view(), name='reportes_view'),
    path('capacitaciones/evaluacion/<int:evaluacion>', ReportesEvaluacionView.as_view(), name='reportes_evaluacion_view'),
    path('evaluaciones', EvaluacionesList.as_view(), name='evaluaciones'),
    path('evaluaciones_json', EvaluacionesListJson.as_view(), name='evaluaciones_json'),
    path('evaluaciones/registrar', EvaluacionCreate.as_view(), name='evaluacion_create'),

]

Proyectos/urls.py
from django.urls import path, include
from Proyectos.views import *

app_name = 'Proyectos'

urlpatterns = [
    path('jornadas', JornadasList.as_view(), name='jornadas'),
    path('jornadas/registrar', JornadaCreate.as_view(), name='jornadas_create'),
    path('jornadas_json', JornadasListJson.as_view(), name='jornadas_json'),
    path('jornadas/<int:pk>', JornadaDetailView.as_view(), name='jornadas_detail'),
    path('jornadas/delete/<int:pk>', JornadaDelete.as_view(), name='jornada_delete'),
]

Reportes/urls.py
from django.urls import path, include
from .views import *

app_name = 'Reportes'

urlpatterns = [
    path('reportes', ReportesView.as_view(), name='reportes_view'),
    path('reportes/jornada/<int:jornada>', ReportesJornadaView.as_view(), name='reportes_jornada_view'),
    path('seguimiento', ReportesSeguimientoView.as_view(), name='reportes_seguimiento_view'),
    path('seguimiento/jornada/<int:jornada>', ReportesSeguimientoJornadaView.as_view(), name='reportes_seguimiento_jornada_view'),
    path('comparar', CompareJornadaView.as_view(), name='compare_jornada_view'),
]

nefrovida/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    path('', include('Beneficiarios.urls')),
    path('', include('Formularios.urls')),
    path('', include('Usuarios.urls')),
    path('', include('Proyectos.urls')),
    path('', include('Reportes.urls')),
    path('', include('Doctores.urls')),

]

Beneficiarios/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from Proyectos.models import *


class Beneficiario(models.Model):  # NEF-29
    NINGUNA = 'NO'
    PRIMARIA_TRUNCA = 'PRIT'
    PRIMARIA_TERMINADA = 'PRI'
    SECUNDARIA_TRUNCA = 'SECT'
    SECUNDARIA_TERMINADA = 'SEC'
    PREPARATORIA_TRUNCA = 'PRET'
    PREPARATORIA_TERMINADA = 'PRE'
    LICENCIATURA_TRUNCA = 'LICT'
    LICENCIATURA_TERMINADA = 'LIC'
    POSGRADO = 'POS'

    ESCOLARIDADES = (
        (NINGUNA, 'Ninguna'),
        (PRIMARIA_TRUNCA, 'Primaria trunca'),
        (PRIMARIA_TERMINADA, 'Primaria terminada'),
        (SECUNDARIA_TRUNCA, 'Secundaria trunca'),
        (SECUNDARIA_TERMINADA, 'Secundaria terminada'),
        (PREPARATORIA_TRUNCA, 'Preparatoria trunca'),
        (PREPARATORIA_TERMINADA, 'Preparatoria terminada'),
        (LICENCIATURA_TRUNCA, 'Licenciatura trunca'),
        (LICENCIATURA_TERMINADA, 'Licenciatura terminada'),
        (POSGRADO, 'Posgrado'),
    )

    NINGUNA_ENF = 0
    DIABETES = 1
    HIPERTENSION = 2
    AMBAS = 3

    ENFERMEDADES = (
        (NINGUNA_ENF, 'Ni diabetes ni hipertensión'),
        (DIABETES, 'Diabetes'),
        (HIPERTENSION, 'Hipertensión'),
        (AMBAS, 'Diabetes e hipertensión'),
    )

    fecha_registro = models.DateTimeField(default=timezone.now)
    apellido_paterno = models.CharField(max_length=255)
    apellido_materno = models.CharField(blank=True, max_length=255)
    nombre = models.CharField(max_length=255)
    sexo = models.BooleanField()
    fecha_nacimiento = models.DateField()
    telefono = models.CharField(blank=True, max_length=10)
    celular = models.CharField(blank=True, max_length=10)
    correo = models.EmailField(blank=True, max_length=255)
    activo_laboralmente = models.BooleanField(default=False)
    nucleo_familiar = models.CharField(blank=True, max_length=255)
    vivienda_propia = models.BooleanField(default=False)
    afroamericano = models.BooleanField(default=False)
    escolaridad = models.CharField(max_length=4, choices=ESCOLARIDADES,
                                   default=NINGUNA)
    diabetico_hipertenso = models.IntegerField(default=0)
    nota = models.CharField(max_length=255, blank=True, null=True)
    jornada = models.ForeignKey(Jornada, on_delete=models.PROTECT, null=True)
    edad_inicial = models.IntegerField(blank=True, null=True)
    de_seguimiento = models.BooleanField(default=False)
    activo = models.BooleanField(default=True)
    causa_baja = models.TextField(blank=True, null=True,max_length=6000)

    @property
    def edad(self):
        today = date.today()
        born = self.fecha_nacimiento
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

    @property
    def edad_ini(self):
        today = self.fecha_registro
        born = self.fecha_nacimiento
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

    @property
    def escuela(self):
        nombre = dict(self.ESCOLARIDADES)
        return nombre[self.escolaridad]

    @property
    def enfermedad(self):
        enf = dict(self.ENFERMEDADES)
        return enf[self.diabetico_hipertenso]

    def save(self, *args, **kwargs):
        self.edad_inicial = self.edad_ini
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nombre + " " + self.apellido_paterno


class Antecedentes(models.Model):
    beneficiario = models.OneToOneField(Beneficiario, on_delete=models.CASCADE, primary_key=True,)
    enfermedad_cardio_abuelo = models.BooleanField(default=False)
    enfermedad_cardio_padre = models.BooleanField(default=False)
    enfermedad_cardio_madre = models.BooleanField(default=False)
    enfermedad_cardio_hermanos = models.BooleanField(default=False)
    hta_abuelo = models.BooleanField(default=False)
    hta_padre = models.BooleanField(default=False)
    hta_madre = models.BooleanField(default=False)
    hta_hermanos = models.BooleanField(default=False)
    diabetes_abuelo = models.BooleanField(default=False)
    diabetes_padre = models.BooleanField(default=False)
    diabetes_madre = models.BooleanField(default=False)
    diabetes_hermanos = models.BooleanField(default=False)
    dislipidemias_abuelo = models.BooleanField(default=False)
    dislipidemias_padre = models.BooleanField(default=False)
    dislipidemias_madre = models.BooleanField(default=False)
    dislipidemias_hermanos = models.BooleanField(default=False)
    obesidad_abuelo = models.BooleanField(default=False)
    obesidad_padre = models.BooleanField(default=False)
    obesidad_madre = models.BooleanField(default=False)
    obesidad_hermanos = models.BooleanField(default=False)
    enfermedad_cerebro_abuelo = models.BooleanField(default=False)
    enfermedad_cerebro_padre = models.BooleanField(default=False)
    enfermedad_cerebro_madre = models.BooleanField(default=False)
    enfermedad_cerebro_hermanos = models.BooleanField(default=False)
    enfermedad_renal_abuelo = models.BooleanField(default=False)
    enfermedad_renal_padre = models.BooleanField(default=False)
    enfermedad_renal_madre = models.BooleanField(default=False)
    enfermedad_renal_hermanos = models.BooleanField(default=False)
    drogadiccion = models.BooleanField(default=False)
    intervencion_quirurgica = models.BooleanField(default=False)
    intervencion_hospitalaria = models.BooleanField(default=False)
    enfermedad_cardiovascular = models.BooleanField(default=False)
    tabaquismo = models.BooleanField(default=False)
    infeccion_urinaria = models.BooleanField(default=False)
    sedentarismo = models.BooleanField(default=False)
    alcoholismo = models.BooleanField(default=False)
    actividiad_fisica = models.BooleanField(default=False)

Proyectos/models.py
from django.db import models
import datetime


class Jornada(models.Model):  # NEF-21
    nombre = models.CharField(max_length=255, null=False)
    fecha = models.DateField(default=datetime.date.today)
    estado = models.CharField(max_length=255, null=False)
    municipio = models.CharField(max_length=255, null=False)
    localidad = models.CharField(max_length=255, null=False)

    def __str__(self):
        return "Jornada - " + str(self.nombre)

Proyectos/forms.py
from django import forms
from django.utils import timezone
from .models import *
from django.core.exceptions import ValidationError
import datetime
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField


class JornadaForm(forms.ModelForm):  # NEF-21
    class Meta:
        model = Jornada
        exclude = []
        fields = [
            'nombre',
            'fecha',
            'estado',
            'municipio',
            'localidad',
        ]
        widgets = {
            'nombre':
                forms.TextInput(attrs={'class': 'form-control'}),
            'estado':
                forms.TextInput(attrs={'class': 'form-control'}),
            'municipio':
                forms.TextInput(attrs={'class': 'form-control'}),
            'localidad':
                forms.TextInput(attrs={'class': 'form-control'}),
            'fecha':
                forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date', 'class': 'form-control'}),
        }

        labels = {
            'nombre': 'Nombre de la jornada',
            'fecha': 'Fecha de inicio de la jornada',
            'estado': 'Estado',
            'municipio': 'Municipio',
            'localidad': 'Localidad',
        }

Proyectos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.http import *
from django.urls import *
from Beneficiarios.models import *
from .models import *
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.contrib.auth.mixins import PermissionRequiredMixin
from datetime import date
from .forms import *
import sweetify
from sweetify.views import SweetifySuccessMixin
from django.core.serializers import serialize
from django.db.models import ProtectedError


class JornadaView(PermissionRequiredMixin, TemplateView):  # NEF-26
    permission_required = "Proyectos.view_jornada"
    model = Jornada
    template_name = "Proyectos/jornadas_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        jornadas = Jornada.objects.all()
        context['jornada'] = jornadas
        return context


class JornadaDetailView(PermissionRequiredMixin, DetailView):  # NEF-27
    permission_required = "Proyectos.view_jornada"
    model = Jornada
    template_name = "Proyectos/jornadas_detail.html"

    def get_context_data(self, **kwargs):
        context = super(JornadaDetailView, self).get_context_data(**kwargs)
        id = self.kwargs["pk"]
        jornada = Jornada.objects.get(id=id)
        beneficiarios = len(Beneficiario.objects.filter(jornada=id))
        context["jornada"] = jornada
        context["beneficiario"] = beneficiarios
        if beneficiarios != 0:
            context['vacio'] = False
        else:
            context['vacio'] = True
        return context


class JornadasList(PermissionRequiredMixin, TemplateView):
    permission_required = "Proyectos.view_jornada"
    template_name = "Proyectos/jornadas_list.html"


class JornadasListJson(PermissionRequiredMixin, BaseDatatableView):  # NEF-34
    permission_required = "Proyectos.view_jornada"
    model = Jornada

    def render_column(self, row, column):
        if column == 'nombre':
            return '<a href=/jornadas/' + str(row.id) + '>' + row.nombre + '</a>'
        elif column == 'fecha':
            return row.fecha
        elif column == 'estado':
            return row.estado
        elif column == 'municipio':
            return row.municipio
        elif column == 'localidad':
            return row.localidad
        elif column == 'beneficiarios':
            beneficiarios = len(Beneficiario.objects.filter(jornada=row.id))
            return beneficiarios
        else:
            return super(JornadasListJson, self).render_column(row, column)


class JornadaCreate(PermissionRequiredMixin, CreateView):  # NEF-21
    permission_required = "Proyectos.add_jornada"
    model = Jornada
    form_class = JornadaForm

    def form_valid(self, form):
        form.save()
        return super(JornadaCreate, self).form_valid(form)

    def form_invalid(self, form):
        sweetify.error(self.request, 'Algo salió mal', icon='error', buttons=False, text=" ")
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def get_success_url(self):
        return reverse_lazy('Proyectos:jornadas')


class JornadaDelete(PermissionRequiredMixin, DeleteView):  # NEF-23
    permission_required = "Proyectos.delete_jornada"
    model = Jornada
    success_url = reverse_lazy('Proyectos:jornadas')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        try:
            self.object.delete()
        except ProtectedError:
            redirect(success_url)
        return HttpResponseRedirect(success_url)

Proyectos/templates/Proyectos/jornada_confirm_delete.html
<!–– NEF-23  ––>
{% extends 'base.html' %}
{% load static %}


{% block includes %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/datatables.min.css"/>
<link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="{% static 'Proyectos/styles.css' %}">
{% endblock includes %}
{% block content %}
    <div class="row">

        <div class="col-md-3"></div>
        <div class="jumbotron col-md-6 mt-3 text-center">
            <form method="post">{% csrf_token %}
                <h5 class="pb-3">¿Estás seguro que deseas borrar "{{ object }}"?</h5>
                <button type="button" class="btn btn-edit" onclick="window.history.back()">Cancelar</button>
                <input class="btn btn-delete" type="submit" value="Borrar" />
            </form>
        </div>
    </div>
{% endblock content %}

Proyectos/templates/Proyectos/jornada_form.html
{% extends 'base.html' %}
{% load static %}
<!-- # NEF-21 -->

{% block includes %}
    <link rel="stylesheet" href="{% static 'Formularios/styles.css' %}">
{% endblock includes %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>Jornadas</h1>
        <form action="" method="POST">
        {% csrf_token %}
        <div class="row pb-3">
          <div class="col">
            <label for="">{{ form.nombre.label }}</label>
            {{ form.nombre }}
          </div>
        </div>
        <div class="row pb-3">
          <div class="col">
            <label for="">{{ form.fecha.label }}</label>
            {{ form.fecha }}
          </div>
        </div>
        <hr>
        <h4>Ubicación de la jornada</h4>

        <div class="form-group">
          <label for="form-address">Localidad</label>
          <input name="localidad" type="search" class="form-control" id="form-address" placeholder="Ingresa la localidad">
        </div>

        <div class="form-group">
          <label for="form-city">Municipio</label>
          <input name="municipio" type="text" class="form-control" id="form-city" placeholder="Ingresa el municipio">
        </div>

        <div class="form-group">
          <label for="form-address2">Estado</label>
          <input name="estado" type="text" class="form-control" id="form-address2" >
        </div>


        <input type="submit" value="Guardar"  class="btn float-right btn-save">

      </form>
    </div>
  </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/places.js@1.16.3"></script>
<script>
(function() {
  var placesAutocomplete = places({
    appId: 'plC86ZBDDYBJ',
    apiKey: 'c0b89e003f0a6363e22343017f9b3375',
    container: document.querySelector('#form-address'),
    templates: {
      value: function(suggestion) {
        return suggestion.name;
      }
    }
  }).configure({
    type: 'address'
  });

  var placesAutocomplete = places({
    appId: 'plC86ZBDDYBJ',
    apiKey: 'c0b89e003f0a6363e22343017f9b3375',
    container: document.querySelector('#form-city'),
    templates: {
      value: function(suggestion) {
        return suggestion.name;
      }
    }
  }).configure({
    type: 'city'
  });
  placesAutocomplete.on('change', function resultSelected(e) {
    document.querySelector('#form-address2').value = e.suggestion.administrative || '';
    // document.querySelector('#form-city').value = e.suggestion.city || '';
  });
})();
</script>

{% endblock content %}

Proyectos/templates/Proyectos/jornadas_detail.html
<!–– NEF-27  ––>

{% extends 'base.html' %}
{% load static %}


{% block includes %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/datatables.min.css"/>
<link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="{% static 'Proyectos/styles.css' %}">
{% endblock includes %}

{% block scripts %}
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="//cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
{% if perms.Beneficiarios.view_beneficiario %}
<script>
    var dt_table = undefined;
    var setUpDataTable = function(){
        var URL = '{% url 'Beneficiarios:beneficiarios_json' %}';

        if(dt_table != undefined){
            dt_table.destroy();
        }
        var data = {};
        if($('#categoria').val() != 'none'){
            data.categoria = $('#categoria').val();
        }

        data.jornada = {{ jornada.id }};

        dt_table = $('#beneficiarios_table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json",
            },
            order: [[ 0, "asc" ]],
            responsive: true,
            columnDefs: [
                {
                    name: 'id',
                    orderable: true,
                    searchable: true,
                    targets: [0]
                },
                {
                    name: 'nombre',
                    orderable: true,
                    searchable: true,
                    targets: [1]
                },
                {
                    name: 'apellido_paterno',
                    orderable: true,
                    searchable: true,
                    targets: [2]
                },
                {
                    name: 'apellido_materno',
                    orderable: true,
                    searchable: true,
                    targets: [3]
                },
                {
                    name: 'sexo',
                    targets: [4],
                    orderable: false,
                    searchable: false,
                },
                {
                    name: 'de_seguimiento',
                    targets: [5],
                    orderable: true,
                    searchable: false,
                },
                {
                    name: 'clasificacion',
                    targets:[6],
                    orderable: false,
                    searchable: false,
                },
                {
                    name: 'edad',
                    targets: [7],
                    orderable: false,
                    searchable: false,
                },
                {
                    name: 'activo',
                    targets: [8],
                    orderable: true,
                    searchable: false,
                }
            ],
            searching: true,
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: URL,
                data: data
            }
        });
    };


    $(document).ready(function() {setUpDataTable()});
</script>

<script>
    $(document).ready(function(){
        $('#categoria').on('change', function(){
            setUpDataTable()
        });
    });
</script>
{% endif %}
{% endblock scripts %}

{% block content %}
<div class="container-fluid pt-4 pb-4">
    <div class="card">
        <div class="card-body card-info">
            <div class="row ml-4 pb-3">
                <div class="col-md-2">
                    {% if perms.Proyectos.change_jornada %}
                    <a href="{% url 'admin:Proyectos_jornada_change' jornada.id %}" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Editar"><i class="fa fa-edit"></i></a>
                    {% endif %}
                <br>
                    {% if perms.Proyectos.delete_jornada and vacio %}
                    <a href="{% url 'Proyectos:jornada_delete' jornada.id %}" class="btn btn-danger mt-3" data-toggle="tooltip" data-placement="right" title="Borrar"><i class="fa fa-trash"></i></a>
                    {% endif %}
                </div>
                <div class="col-md-8 text-center viewparameters">
                    <h2>{{ jornada.nombre }} </h2>
                </div>
            </div>
            <div class="row justify-content-center py-2">
                <div class="col-12 col-md-1 ml-4 mr-1"><i class="fas fa-hashtag"></i> {{ jornada.id }}</div>
                <div class="col-12 col-md-auto mr-5"><i class="fas fa-calendar-alt"></i> {{ jornada.fecha }}</div>
                <div class="col-12 col-md-auto mr-5"><i class="fas fa-map-marker"></i> {{ jornada.localidad}}, {{ jornada.municipio}}, {{ jornada.estado}} </div>
                <div class="col-md-2 viewparameters text-right">
                    <a href="{% url 'Reportes:reportes_jornada_view' jornada=jornada.id %}"><i class="fas fa-chart-bar"></i> Reportes </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% block jornada_content %}
<h5><a href="{% url 'admin:Formularios_evaluacionplaticas_add' %}">Evaluaciones</a> <a href="{% url 'admin:Formularios_evaluacionplaticas_add' %}"><i class="fas fa-plus-square icon-add"></i></a></h5>
<h2>Beneficiarios <a href="{% url 'Beneficiarios:beneficiarios_create' id_jornada=jornada.id %}"><i class="fas fa-plus-square icon-add"></i></a></h2>
<div class="row mb-2">
    <div class="col-12 col-md-3 offset-md-4 col-lg-2 offset-lg-8 text-right align-center">
        <label for="categoria">Filtrar por clasificación:</label>
    </div>
    <div class="col-12 col-md-5 col-lg-2">
        <select id="categoria" class="custom-select form-control">
            <option value="none" selected>Todos</option>
            <option value="Sin datos">Sin datos</option>
            <option value="G1">G1</option>
            <option value="G2">G2</option>
            <option value="G3">G3</option>
            <option value="G4">G4</option>
            <option value="G5">G5</option>
            <option value="discrepancia">Discrepancia</option>
        </select>
    </div>
</div>
{% if perms.Beneficiarios.view_beneficiario %}
<table id="beneficiarios_table" class="datatable table table-hover table-striped">
    <thead>
    <th>Folio</th>
    <th>Nombre</th>
    <th>Apellido paterno</th>
    <th>Apellido materno</th>
    <th>Sexo</th>
    <th>De Seguimiento</th>
    <th>Clasificación</th>
    <th>Edad</th>
    <th>Activo</th>
    </thead>
    <tbody></tbody>
</table>
{% endif %}
{% endblock jornada_content %}

{% endblock content %}

Proyectos/templates/Proyectos/jornadas_list.html
<!–– NEF-26 ––>

{% extends 'base.html' %}
{% load static %}


{% block includes %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/datatables.min.css"/>
<link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="{% static 'Proyectos/styles.css' %}">
{% endblock includes %}

{% block scripts %}
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="//cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script>
$(document).ready(function() {
    var URL = '{% url 'Proyectos:jornadas_json' %}';
    var dt_table = $('#jornadas_table').dataTable({
        "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json",
        },
        order: [[ 1, "desc" ]],
        responsive: true,
        columnDefs: [
            {
                name: 'nombre',
                orderable: true,
                searchable: true,
                targets: [0]
            },
            {
                name: 'fecha',
                orderable: true,
                searchable: true,
                targets: [1]
            },
            {
                name: 'estado',
                orderable: true,
                searchable: true,
                targets: [2]
            },
            {
                name: 'municipio',
                orderable: true,
                searchable: true,
                targets: [3]
            },
            {
                name: 'localidad',
                targets: [4],
                orderable: true,
                searchable: true,
            },
            {
                name: 'beneficiarios',
                targets:[5],
                orderable: true,
                searchable: false,
            }
        ],
        searching: true,
        processing: true,
        serverSide: true,
        stateSave: true,
        ajax: URL
    });
});
</script>
{% endblock scripts %}

{% block content %}
<br>
<h2>Jornadas <div class="clearfix d-inline-block">
  <a href="{% url 'Proyectos:jornadas_create' %}"><i class="fas fa-plus-square icon-add"></i></a>
</div></h2>
<br><br>
<table id="jornadas_table" class="datatable table table-hover table-striped">
    <thead>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Estado</th>
        <th>Municipio</th>
        <th>Localidad</th>
        <th>Beneficiarios</th>
    </thead>
    <tbody></tbody>
</table>
{% endblock content %}