Beneficiarios/urls.py
from django.urls import path

from Beneficiarios.views import *

app_name = 'Beneficiarios'

urlpatterns = [
    path('<int:id_jornada>/beneficiarios/registrar', BeneficiariosNew.as_view(),
         name='beneficiarios_create'),
    path('beneficiarios/<int:id>/antecedentes/registrar', AntecedentesNew.as_view(),
         name='antecedentes_create'),
    path('beneficiarios', BeneficiariosList.as_view(), name='beneficiarios'),
    path('beneficiarios_json', BeneficiariosListJson.as_view(),
         name='beneficiarios_json'),
    path('beneficiarios/<int:pk>',
         BeneficiariosDetailView.as_view(), name='beneficiario'),
    path('beneficiarios/<int:pk>/expediente',
         BeneficiariosRecordView.as_view(), name='beneficiario_record'),
    path('r_est/<int:pk>',
         rEstJSON.as_view(), name='rEst'),
    path('r_tam/<int:pk>',
         rTamJSON.as_view(), name='rTam'),
    path('r_qui/<int:pk>',
         rQuiJSON.as_view(), name='rQui'),
    path('r_mic/<int:pk>',
         rMicJSON.as_view(), name='rMic'),
    path('r_hem/<int:pk>',
         rHemJSON.as_view(), name='rHem'),
    path('r_glu/<int:pk>',
         rGluJSON.as_view(), name='rGlu'),
    path('r_con/<int:pk>',
         rConJSON.as_view(), name='rCon'),
    path('r_adh/<int:pk>',
         rAdhJSON.as_view(), name='rAdh'),
    path('r_ham/<int:pk>',
         rHamJSON.as_view(), name='rHam'),
    path('r_mal/<int:pk>',
         rMalJSON.as_view(), name='rMal'),
    path('r_reg/<int:pk>',
         rRegJSON.as_view(), name='rReg'),


         
]

Doctores/urls.py
from django.urls import path, include
from .views import *

app_name = 'Doctores'

urlpatterns = [
    path('capacitaciones', ReportesView.as_view(), name='reportes_view'),
    path('capacitaciones/evaluacion/<int:evaluacion>', ReportesEvaluacionView.as_view(), name='reportes_evaluacion_view'),
    path('evaluaciones', EvaluacionesList.as_view(), name='evaluaciones'),
    path('evaluaciones_json', EvaluacionesListJson.as_view(), name='evaluaciones_json'),
    path('evaluaciones/registrar', EvaluacionCreate.as_view(), name='evaluacion_create'),

]

Proyectos/urls.py
from django.urls import path, include
from Proyectos.views import *

app_name = 'Proyectos'

urlpatterns = [
    path('jornadas', JornadasList.as_view(), name='jornadas'),
    path('jornadas/registrar', JornadaCreate.as_view(), name='jornadas_create'),
    path('jornadas_json', JornadasListJson.as_view(), name='jornadas_json'),
    path('jornadas/<int:pk>', JornadaDetailView.as_view(), name='jornadas_detail'),
    path('jornadas/delete/<int:pk>', JornadaDelete.as_view(), name='jornada_delete'),
]

Reportes/urls.py
from django.urls import path, include
from .views import *

app_name = 'Reportes'

urlpatterns = [
    path('reportes', ReportesView.as_view(), name='reportes_view'),
    path('reportes/jornada/<int:jornada>', ReportesJornadaView.as_view(), name='reportes_jornada_view'),
    path('seguimiento', ReportesSeguimientoView.as_view(), name='reportes_seguimiento_view'),
    path('seguimiento/jornada/<int:jornada>', ReportesSeguimientoJornadaView.as_view(), name='reportes_seguimiento_jornada_view'),
    path('comparar', CompareJornadaView.as_view(), name='compare_jornada_view'),
]

nefrovida/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    path('', include('Beneficiarios.urls')),
    path('', include('Formularios.urls')),
    path('', include('Usuarios.urls')),
    path('', include('Proyectos.urls')),
    path('', include('Reportes.urls')),
    path('', include('Doctores.urls')),

]

Doctores/models.py
from django.db import models
from django.core.validators import *
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
import uuid



# Create your models here.

class Evaluacion(models.Model):
    class Meta:
        verbose_name = 'Evaluación'
        verbose_name_plural = 'Evaluaciones'

    nombre = models.CharField(max_length=255)
    fecha = models.DateField(default=datetime.date.today)
    def __str__(self):
        return self.nombre + str(self.fecha)


class Formulario(models.Model):
    class Meta:
        verbose_name = 'Capacitación'
        verbose_name_plural = 'Capacitaciones'
    labels = {
        'p1': 'Número de personas diabéticas e hipertensas que atiende usted mensualmente: ',
        'p2': '¿Cuáles son las metas de tratamiento de la nefropatía diabética?',
        'p3': '¿Qué porcentaje de pacientes con Hipertensión Arterial se estima presenta Nefropatía Hipertensiva como causa de Enfermedad Renal Crónica?',
        'p4': 'Por lo general, la mortalidad anual ajustada de los pacientes que dependen de hemodiálisis tiende a ser:',
        'p5': '¿Cuál de las siguientes es la causa principal de muerte en los pacientes que dependen de diálisis?',
        'p6': 'Cuando se sospecha de un daño del riñón, ¿cuáles estudios debe realizarse el paciente?',
        'p7': 'Cuales enfermedades conllevan a enfermedad renal crónica de manera más frecuente:',
        'p8': 'En qué momento debe ser derivado un paciente con disminución de la función renal al Nefrólogo: ',
        'p9': 'Porque es importante ajustar las dosis de medicamentos en la ERC: ',
        'p10': 'En relación al paciente Urémico cual es la opción correcta',
        'p11': '¿Qué es un trasplante renal?',
        'p12': '¿Qué cantidad de proteína que se recomienda para pacientes sin terapia sustitutiva? ',
        'p13': '¿Qué cantidad de proteína que se recomienda para pacientes en diálisis peritoneal?',
        'p14': '¿Qué cantidad de proteína que se recomienda para pacientes en hemodiálisis?',
        'p15': 'Las fuentes de qué elementos se deben cuidar en el paciente con enfermedad renal:',
        'p16': 'La recomendación de la cantidad de líquido que debe tomar un paciente con ERC es: ',
        'p17': '¿Cuáles son las razones psicológicas que hacen que las personas con ERC no se adhieran al tratamiento?',
        'p18': '¿Qué entendemos por "dar malas noticias"?',
        'p19': '¿Cuáles son los dos principios que el equipo médico necesita identificar para proporcionar información?',
        'p20': 'Mencione 5 barreras de la comunicación en la relación médico-paciente',
    }

    choices_2 = {1: 'A', 2: 'B', 3: 'C', 4: 'D', -1: 'E'}#
    choices_3 = {-1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}#
    choices_4 = {1: 'A', -1: 'B', 3: 'C', 4: 'D', 5: 'E'}#
    choices_5 = {1: 'A', 2: 'B', -1: 'C', 4: 'D', 5: 'E'}#
    choices_6 = {1: 'A', 2: 'B', 3: 'C', -1: 'D'}#
    choices_7 = {1: 'A', 2: 'B', 3: 'C', -1: 'D'}#
    choices_8 = {1: 'A', -1: 'B', 3: 'C'}#
    choices_9 = {1: 'A', -1: 'B', 3: 'C'}#
    choices_10 = {1: 'A', 2: 'B', -1: 'C'}#
    choices_11 = {1: 'A', 2: 'B', -1: 'C'}
    choices_12 = {1: 'A', -1: 'B', 3: 'C'}
    choices_13 = {-1: 'A', 2: 'B', 3: 'C'}
    choices_14 = {1: 'A', 2: 'B', -1: 'C'}
    choices_15 = {-1: 'A', 2: 'B', 3: 'C'}
    choices_16 = {-1: 'A', 2: 'B', 3: 'C'}
    choices_17 = {1: 'A', 2: 'B', -1: 'C'}
    choices_18 = {1: 'A', 2: 'B', -1: 'C'}#
    choices_19 = {1: 'A', -1: 'B', 3: 'C'}#
    choices_20 = {-1: 'A', 2: 'B', 3: 'C'}#


    evaluacion = models.ForeignKey(Evaluacion, on_delete=models.CASCADE)
    periodo = models.BooleanField(default=False)
    p1 = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    p2 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p3 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p4 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p5 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p6 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p7 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p8 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p9 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p10 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p11 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p12 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p13 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p14 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p15 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p16 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p17 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p18 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p19 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)
    p20 = models.IntegerField(validators=[MaxValueValidator(9)], default=-1)

    def __str__(self):
        return str(self.evaluacion) + str(self.id)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head lang="es">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Percept">

    <title>{% block title %}Nefrovida{% endblock title %}</title>
    <link rel="icon" type="image/png" href="#">

    <link rel="stylesheet" type="text/css" href="{% static 'css/side_nav_bars.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/back_button.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon_io/site.webmanifest' %}">
    {% block includes %}
    {% endblock includes %}
</head>

<body>
<nav class="navbar nefro_navbar d-lg-flex flex-row bd-highlight">
    <img src="{% static 'img/logo_NefroVida.png' %}" class="nefro_logo p-1 bd-highlight">

    <div class="p-2 flex-grow-1 bd-highlight d-none d-lg-block"></div>
    <div class="p-2 bd-highlight d-none d-lg-block josefino"><i class="material-icons">face</i>
        {% if request.user.get_full_name %}
            {{ request.user.get_full_name }}
        {% else %}
            {{ request.user.username }}
        {% endif %}
    </div>
    <div class="p-2 bd-highlight">
        <button type="button" class="btn btn-outline-danger btn-sm" onclick="location.href='{% url 'logout' %}'">Cerrar
            sesión
        </button>
    </div>
</nav>

<div id="sidebar_div">
    {% block sidebar %}
        <div id="mySidenav" class="sidenav">
            <a href="#" id="sideopener"><i class='fas fa-angle-double-right icon-size'></i></a href="#">
            <div class="text">
                {% if perms.Beneficiarios.view_beneficiario %}
                    <a href="{% url 'Beneficiarios:beneficiarios' %}"
                       {% if request.path|slice:":14" == '/beneficiarios' %}class="sidebar-list active"
                       {% else %}class="sidebar-list" {% endif %}><i class="material-icons">folder_shared</i> <span
                            class="sidebar-hide hidden">Beneficiarios</span></a>
                {% endif %}

                {% if perms.Proyectos.view_jornada %}
                    <a href="{% url 'Proyectos:jornadas' %}"
                       {% if request.path|slice:":9" == '/jornadas' %}class="sidebar-list active"
                       {% else %}class="sidebar-list" {% endif %}><i class="material-icons">access_time</i> <span
                            class="sidebar-hide hidden">Jornadas</span></a>
                {% endif %}

                {% if perms.Doctores.view_evaluacion %}
                    <a href="{% url 'Doctores:evaluaciones' %}"
                       {% if request.path|slice:":13" == '/evaluaciones' %}class="sidebar-list active"
                       {% else %}class="sidebar-list" {% endif %}><i class="ml-1 mr-2 far fa-sticky-note"></i><span
                            class="sidebar-hide hidden">Evaluaciones</span></a>
                {% endif %}

                {% if perms.Reportes.view_reportes %}
                    <a href="{% url 'Reportes:reportes_seguimiento_view' %}"
                        {% if request.path|slice:":21" == '/seguimiento' %}class="sidebar-list active"
                        {% else %}class="sidebar-list" {% endif %}><i class="material-icons">archive</i> <span
                            class="sidebar-hide hidden">Reportes de seguimiento</span></a>
                    <a href="{% url 'Reportes:reportes_view' %}"
                        {% if request.path|slice:":9" == '/reportes' %}class="sidebar-list active"
                        {% else %}class="sidebar-list" {% endif %}><i class="material-icons">timeline</i> <span
                            class="sidebar-hide hidden">Reportes</span></a>
                    <a href="{% url 'Reportes:compare_jornada_view' %}"
                        {% if request.path|slice:":9" == '/comparar' %}class="sidebar-list active"
                        {% else %}class="sidebar-list" {% endif %}><i class="material-icons">multiline_chart</i> <span
                            class="sidebar-hide hidden">Comparar Jornadas</span></a>


                         
                {% endif %}

                {% if perms.Doctores.view_evaluacion %}
                    <a href="{% url 'Doctores:reportes_view' %}"
                       {% if request.path|slice:":15" == '/capacitaciones' %}class="sidebar-list active"
                       {% else %}class="sidebar-list" {% endif %}><i class="fas fa-chart-pie"></i> <span
                            class="sidebar-hide hidden">Reportes de capacitaciones</span></a>
                {% endif %}

                {% if perms.Usuarios.view_user and False %}
                    <a href="#" class="sidebar-list"><i class="material-icons">group</i> <span
                            class="sidebar-hide hidden">Usuarios</span></a>
                {% endif %}

            </div>
        </div>
    {% endblock sidebar %}
</div>

<div id="content_div">
    <div id="main">
        {% if request.path != "/" %}
            <div class="container-fluid">
                <button type="button" class="btn btn-outline-info btn-circle" onclick="window.history.back()"><i
                        class="fas fa-arrow-left"></i></button>
            </div>
        {% endif %}
        <div class="container-fluid">
            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <div class="row">
        <footer class="col">
            {% block footer %}
            {% endblock footer %}
        </footer>
    </div>
</div>

{% block modal %}
{% endblock modal %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'js/side_nav_bars.js' %}"></script>
<script src="{% static 'Beneficiarios/beneficiarios_detail.js' %}"></script>
<script>
    $(function () {
        $('[data-toggle="tooltip"').tooltip();
    });
</script>
{% block scripts %}
{% endblock scripts %}
{% load sweetify %}
{% sweetify %}
</body>

</html>