Doctores/urls.py
from django.urls import path, include
from .views import *

app_name = 'Doctores'

urlpatterns = [
    path('capacitaciones', ReportesView.as_view(), name='reportes_view'),
    path('capacitaciones/evaluacion/<int:evaluacion>', ReportesEvaluacionView.as_view(), name='reportes_evaluacion_view'),
    path('evaluaciones', EvaluacionesList.as_view(), name='evaluaciones'),
    path('evaluaciones_json', EvaluacionesListJson.as_view(), name='evaluaciones_json'),
    path('evaluaciones/registrar', EvaluacionCreate.as_view(), name='evaluacion_create'),

]

Formularios/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required, permission_required

app_name = "Formularios"
urlpatterns = [
    path('beneficiarios/<int:beneficiario>/evidencias/registrar', EvidenciaCreate.as_view(),
         name='evidencias_register'),
    path('beneficiarios/<int:beneficiario>/evidencias/', EvidenciaView.as_view(),
         name='view_evidencias'),
    path('beneficiarios/<int:beneficiario>/hemoglobinaglucosilada/registrar',
         login_required(HemoglobinaGlucosiladaCreate.as_view()),
         name='register_hemoglobinaglucosilada'),
    path('beneficiarios/<int:beneficiario>/microalbuminuria/registrar', MicroalbuminuriaCreate.as_view(),
         name='register_microalbuminuria'),
    path('beneficiarios/<int:beneficiario>/quimicasanguinea/registrar',
         login_required(QuimicaSanguineaCreate.as_view()), name='cqs'),
    path('quimicasanguinea/<int:pk>/eliminar', QuimicaSanguineaDelete.as_view(), name="delete_quimicasanguinea"),
    path('beneficiarios/<int:beneficiario>/glucosacapilar/registrar', GlucosaCapilarCreate.as_view(),
         name='register_glucosacapilar'),
    path('beneficiarios/<int:beneficiario>/malnutricioninflamacion/registrar', MalnutricionInflamacionCreate.as_view(),
         name='register_malnutricioninflamacion'),
    path('beneficiarios/<int:beneficiario>/clasificacion/registrar', ClasificacionCreate.as_view(),
         name='clasificacion_register'),

    path('beneficiarios/<int:beneficiario>/factorderiesgo/registrar', FactorDeRiesgoCreate.as_view(),
         name='register_factorderiesgo'),
    path('beneficiarios/<int:beneficiario>/tamizajenutricional/registrar', TamizajeNutricionalCreate.as_view(),
         name='register_tamizajenutricional'),
    path('beneficiarios/<int:beneficiario>/adherenciatratamiento/registrar', AdherenciaTratamientoCreate.as_view(),
         name='register_adherenciatratamiento'),
    path('adherenciatratamiento/<int:adherenciatratamiento>',
         AdherenciaTratamientoView.as_view(), name="view_adherenciatratamiento"),
    path('factorderiesgo/<int:factorderiesgo>',
         FactorDeRiesgoView.as_view(), name="view_factorderiesgo"),
    path('hemoglobinaglucosilada/<int:hemoglobinaglucosilada>',
         HemoglobinaGlucosiladaView.as_view(), name="view_hemoglobinaglucosilada"),
    path('malnutricioninflamacion/<int:malnutricioninflamacion>',
         MalnutricionInflamacionView.as_view(), name="view_malnutricioninflamacion"),
    path('malnutricioninflamacion/<int:pk>/eliminar',
         MalnutricionInflamacionDelete.as_view(), name="delete_malnutricioninflamacion"),
    path('microalbuminuria/<int:microalbuminuria>', MicroalbuminuriaView.as_view(), name="view_microalbuminuria"),
    path('microalbuminuria/<int:pk>/eliminar', MicroalbuminuriaDelete.as_view(), name="delete_microalbuminuria"),
    path('quimicasanguinea/<int:quimicaSanguinea>', QuimicaSanguineaView.as_view(), name='vqs'),
    path('glucosacapilar/<int:glucosacapilar>', GlucosaCapilarView.as_view(), name="view_glucosacapilar"),
    path('tamizajenutricional/<int:tamizajenutricional>',
         TamizajeNutricionalView.as_view(), name="view_tamizajenutricional"),
    path('beneficiarios/<int:beneficiario>/escalahamilton/registrar', EscalaHamiltonCreate.as_view(),
         name='register_escalahamilton'),
    path('escalahamilton/<int:escalaHamilton>',
         EscalaHamiltonView.as_view(), name="view_escalahamilton"),
    path('beneficiarios/<int:beneficiario>/consultamedica/registrar', ConsultaMedicaCreate.as_view(),
         name='register_consultamedica'),
    path('consultamedica/<int:consultamedica>',
         ConsultaMedicaView.as_view(), name="view_consultamedica"),
    path('consultamedica/<int:pk>/eliminar', ConsultaMedicaDelete.as_view(), name="delete_consultamedica"),
    path('factorderiesgo/<int:pk>/eliminar', FactorDeRiesgoDelete.as_view(), name="delete_factorderiesgo"),
    path('tamizajenutricional/<int:pk>/eliminar', TamizajeNutricionalDelete.as_view(),
         name="delete_tamizajenutricional"),
    path('glucosacapilar/<int:pk>/eliminar', GlucosaCapilarDelete.as_view(), name="delete_glucosacapilar"),
    path('hemoglobinaglucosilada/<int:pk>/eliminar',
         HemoglobinaGlucosiladaDelete.as_view(), name="delete_hemoglobinaglucosilada"),
    path('escalahamilton/<int:pk>/eliminar', EscalaHamiltonDelete.as_view(), name="delete_escalahamilton"),
    path('adherenciatratamiento/<int:pk>/eliminar',
         AdherenciaTratamientoDelete.as_view(), name="delete_adherenciatratamiento"),
    path('evidencias/', EvidenciasList.as_view(), name='evidencias'),
    path('evidencias_json/<int:pk>', EvidenciasListJson.as_view(), name='evidencias_json'),
    path('evidencias/eliminar', EvidenciaDelete.as_view(), name="delete_evidencias"),
    path('evidencias/descargar', EvidenciaDownload.as_view(), name="download_evidencias"),
    path('evaluaciones/', EvaluacionesPlaticasCreate.as_view(),
         name='register_evaluaciones'),

    path('beneficiarios/<int:beneficiario>/nota/registrar', NotaCreate.as_view(),
         name='register_notas'),
    path('nota/<int:nota>',
         NotaView.as_view(), name="view_notas"),
    path('nota/<int:pk>/eliminar', NotaDelete.as_view(), name="delete_notas"),

    path('beneficiarios/<int:beneficiario>/registromensual/registrar', RegistroMensualCreate.as_view(),
         name='register_registromensual'),
    path('registromensual/<int:registromensual>',
         RegistroMensualView.as_view(), name="view_registromensual"),
    path('registromensual/<int:pk>/eliminar',
         RegistroMensualDelete.as_view(), name="delete_registromensual"),
]

nefrovida/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    path('', include('Beneficiarios.urls')),
    path('', include('Formularios.urls')),
    path('', include('Usuarios.urls')),
    path('', include('Proyectos.urls')),
    path('', include('Reportes.urls')),
    path('', include('Doctores.urls')),

]

Formularios/models.py
from django.db import models
from Beneficiarios.models import *
from Proyectos.models import *
import datetime
from django.core.validators import *
from django.contrib.auth.models import User
from django.utils import timezone
import uuid


def get_uuid():
    return uuid.uuid1().hex


class Evidencia(models.Model):  # NEF-99
    beneficiario = models.ForeignKey(Beneficiario, verbose_name='Beneficiario', on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(verbose_name='Fecha de creación', default=timezone.now)
    fecha_subida = models.DateTimeField(verbose_name='Fecha de subida', null=True)
    nombre = models.TextField(max_length=255, blank=False)
    descripcion = models.TextField(verbose_name='Descripción', max_length=1024, blank=True)
    urn = models.TextField(max_length=255, unique=True, null=True, default=get_uuid)
    existe = models.BooleanField(default=False)


class QuimicaSanguineaManager(models.Manager):  # NEF-69

    def get_queryset(self):
        return super().get_queryset().filter(activo=True)


class QuimicaSanguinea(models.Model):  # NEF-66, NEF-68, NEF-69

    class Meta:
        verbose_name = 'Química Sanguínea'
        verbose_name_plural = 'Química Sanguínea'

    beneficiario = models.ForeignKey(Beneficiario, verbose_name='Paciente', on_delete=models.CASCADE)
    fecha_creacion = models.DateField(verbose_name='Fecha de Creación', default=datetime.date.today)
    fecha = models.DateField(verbose_name='Fecha del Estudio', default=datetime.date.today)
    doctor = models.CharField(verbose_name='Doctor', max_length=180)
    metodo = models.CharField(verbose_name='Método', max_length=100)

    glucosa = models.DecimalField(verbose_name='Glucosa', max_digits=5, decimal_places=2,
                                  validators=[MinValueValidator(0)])
    max_glucosa = models.DecimalField(verbose_name='Glucosa Máximo', max_digits=5, decimal_places=2,
                                      validators=[MinValueValidator(0)])
    min_glucosa = models.DecimalField(verbose_name='Glucosa Mínimo', max_digits=5, decimal_places=2,
                                      validators=[MinValueValidator(0)])
    comentario_glucosa = models.TextField(verbose_name='Glucosa Comentarios', max_length=255, null=True, blank=True)
    max_glucosa.default = 100
    min_glucosa.default = 70

    urea = models.DecimalField(verbose_name='Urea', max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    max_urea = models.DecimalField(verbose_name='Urea Máximo', max_digits=5, decimal_places=2,
                                   validators=[MinValueValidator(0)])
    min_urea = models.DecimalField(verbose_name='Urea Mínimo', max_digits=5, decimal_places=2,
                                   validators=[MinValueValidator(0)])
    comentario_urea = models.TextField(verbose_name='Urea Comentarios', max_length=255, null=True, blank=True)
    max_urea.default = 45
    min_urea.default = 15

    bun = models.DecimalField(verbose_name='Bun', max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    max_bun = models.DecimalField(verbose_name='Bun Máximo', max_digits=5, decimal_places=2,
                                  validators=[MinValueValidator(0)])
    min_bun = models.DecimalField(verbose_name='Bun Mínimo', max_digits=5, decimal_places=2,
                                  validators=[MinValueValidator(0)])
    comentario_bun = models.TextField(verbose_name='Bun Comentarios', max_length=255, null=True, blank=True)
    max_bun.default = 21
    min_bun.default = 7

    creatinina = models.DecimalField(verbose_name='Creatinina', max_digits=5, decimal_places=2,
                                     validators=[MinValueValidator(0)])
    max_creatinina_h = models.DecimalField(verbose_name='Creatinina Máximo Hombres', max_digits=5, decimal_places=2,
                                           validators=[MinValueValidator(0)])
    min_creatinina_h = models.DecimalField(verbose_name='Creatinina Mínimo Hombres', max_digits=5, decimal_places=2,
                                           validators=[MinValueValidator(0)])
    max_creatinina_m = models.DecimalField(verbose_name='Creatinina Máximo Mujeres', max_digits=5, decimal_places=2,
                                           validators=[MinValueValidator(0)])
    min_creatinina_m = models.DecimalField(verbose_name='Creatinina Mínimo Mujeres', max_digits=5, decimal_places=2,
                                           validators=[MinValueValidator(0)])
    comentario_creatinina = models.TextField(verbose_name='Creatinina Comentarios', max_length=255, null=True,
                                             blank=True)
    activo = models.BooleanField(null=False, default=True)
    objects = QuimicaSanguineaManager()
    max_creatinina_h.default = 1.2
    min_creatinina_h.default = 0.7
    max_creatinina_m.default = 1
    min_creatinina_m.default = 0.5

    acido_urico = models.DecimalField(verbose_name='Ácido Úrico', max_digits=5, decimal_places=2,
                                      validators=[MinValueValidator(0)], blank=True, null=True, default=None)
    max_acido_urico_h = models.DecimalField(verbose_name='Ácido Úrico Máximo Hombres', max_digits=5, decimal_places=2,
                                            validators=[MinValueValidator(0)])
    min_acido_urico_h = models.DecimalField(verbose_name='Ácido Úrico Mínimo Hombres', max_digits=5, decimal_places=2,
                                            validators=[MinValueValidator(0)])
    max_acido_urico_m = models.DecimalField(verbose_name='Ácido Úrico Máximo Mujeres', max_digits=5, decimal_places=2,
                                            validators=[MinValueValidator(0)])
    min_acido_urico_m = models.DecimalField(verbose_name='Ácido Úrico Mínimo Mujeres', max_digits=5, decimal_places=2,
                                            validators=[MinValueValidator(0)])
    comentario_acido_urico = models.TextField(verbose_name='Ácido Úrico Comentarios', max_length=255, null=True,
                                              blank=True)

    max_acido_urico_h.default = 7.0
    min_acido_urico_h.default = 3.4
    max_acido_urico_m.default = 6.0
    min_acido_urico_m.default = 2.4

    activo = models.BooleanField(null=False, default=True)
    usado_para_estadificacion = models.BooleanField(null=False, default=False)

    objects = QuimicaSanguineaManager()

    metodo.default = "Colorimétrico"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        ma = Microalbuminuria.objects.filter(beneficiario=self.beneficiario.id)
        latest_clasification = Clasificacion.objects.filter(beneficiario=self.beneficiario.id)

        if ma.exists() and self.activo:
            ma = ma.latest('id')
            if clasification(self.beneficiario, self, ma):
                if latest_clasification.exists():
                    latest_clasification = latest_clasification.latest('id')
                    latest_clasification.activo = False
                    latest_clasification.save()

    def __str__(self):
        return str(self.beneficiario) + " - Química Sanguínea " + str(self.id)

    def delete(self, *args, **kwargs):
        Clasificacion.objects.filter(id_qs=self.id).delete()
        self.activo = False
        self.save()


class MicroalbuminuriaManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(activo=True)


class Microalbuminuria(models.Model):  # NEF-74

    class Meta:
        verbose_name = 'Microalbuminuria'
        verbose_name_plural = 'Microalbuminuria'

    beneficiario = models.ForeignKey(Beneficiario, on_delete='CASCADE')
    fecha = models.DateField(default=datetime.date.today)
    metodo = models.CharField(max_length=100)
    doctor = models.CharField(max_length=180)
    micro_albumina = models.DecimalField()
    micro_albumina.max_digits = 5
    micro_albumina.decimal_places = 2
    micro_albumina.validators = [MinValueValidator(0)]
    micro_albumina_min = models.DecimalField()
    micro_albumina_min.max_digits = 5
    micro_albumina_min.decimal_places = 2
    micro_albumina_min.validators = [MinValueValidator(0)]
    micro_albumina_min.default = 0
    micro_albumina_max = models.DecimalField()
    micro_albumina_max.max_digits = 5
    micro_albumina_max.decimal_places = 2
    micro_albumina_max.validators = [MinValueValidator(0)]
    micro_albumina_max.default = 30
    micro_albumina_comentario = models.CharField(max_length=255, null=True)
    micro_albumina_comentario.blank = True
    creatinina = models.DecimalField()
    creatinina.max_digits = 5
    creatinina.decimal_places = 2
    creatinina.validators = [MinValueValidator(0)]
    creatinina_min = models.DecimalField()
    creatinina_min.max_digits = 5
    creatinina_min.decimal_places = 2
    creatinina_min.validators = [MinValueValidator(0)]
    creatinina_min.default = 10
    creatinina_max = models.DecimalField()
    creatinina_max.max_digits = 5
    creatinina_max.decimal_places = 2
    creatinina_max.validators = [MinValueValidator(0)]
    creatinina_max.default = 300
    creatinina_comentario = models.CharField(max_length=255, null=True)
    creatinina_comentario.blank = True
    relacion = models.DecimalField()
    relacion.max_digits = 5
    relacion.decimal_places = 2
    relacion.validators = [MinValueValidator(0)]
    relacion_normal_min = models.DecimalField()
    relacion_normal_min.max_digits = 5
    relacion_normal_min.decimal_places = 2
    relacion_normal_min.validators = [MinValueValidator(0)]
    relacion_normal_min.default = 0
    relacion_normal_max = models.DecimalField()
    relacion_normal_max.max_digits = 5
    relacion_normal_max.decimal_places = 2
    relacion_normal_max.validators = [MinValueValidator(0)]
    relacion_normal_max.default = 30
    relacion_anormal_min = models.DecimalField()
    relacion_anormal_min.max_digits = 5

Formularios/templates/Formularios/evidencia_form.html
{% extends "Beneficiarios/beneficiario_detail.html" %}
{% load static %}
{% block includes %}
    <link rel="stylesheet" href="{% static 'Formularios/styles.css' %}">
    <link rel="stylesheet" href="{% static 'Beneficiarios/styles.css' %}">
{% endblock includes %}

{% block beneficiario-content %}

<div class="container">
    <div class="card mt-5">
        <h5 class="card-header text-center">Evidencias</h5>
        <div class="card-body">
            <form id="no_ia">
                {% csrf_token %}
                <input type="hidden" name="tipo" id="tipo">
                <input type="hidden" name="size" id="size">
                <input type="hidden" name="beneficiario" value="{{ beneficiario.id }}" id="beneficiario">
                <div class="container-fluid">
                    <div class="row pb-4">
                        <div class="col-3 text-right labelsFormulario">
                            {{ form.nombre.label }}
                        </div>
                        <div class="col-6">
                            {{ form.nombre }}
                            <div class="invalid-feedback">Debe ingresar un nombre.</div>
                        </div>
                    </div>
                    <div class="row pb-4">
                        <div class="col-3 text-right labelsFormulario">
                            {{ form.descripcion.label }}
                        </div>
                        <div class="col-6">
                            {{ form.descripcion }}
                        </div>
                    </div>
                </div>
            </form>
            <div class="container-fluid">
                <div class="row pb-4">
                    <div class="col-3 text-right labelsFormulario">
                        Archivo:
                    </div>
                    <div class="col-6">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="evidencia" id="evidencia">
                        <label class="custom-file-label" for="custoevidenciamFile" id="evidencia_label">Selecciona archivo.</label>
                        <div id="archivo" class="invalid-feedback">Debe seleccionar un archivo.</div>
                    </div>
                    </div>
                </div>
                <div class="row pb-4">
                    <div class="col-3"></div>
                    <div class="col-6">
                        <div class="progress">
                            <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="0"
                            aria-valuemin="0" aria-valuemax="100" style="width:0%">
                                0%
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row pb-4">
                    <div class="col-9">
                        <button id="save" class="btn float-right btn-save">Guardar</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock beneficiario-content %}


{% block scripts %}
<script src="{% static 'js/formularios.js' %}" ></script>
<script src="{% static 'js/evidencias.js' %}" ></script>
{% endblock scripts %}

Formularios/templates/Formularios/evidencia_list.html
<!--
  NEF-58
-->
{% extends "Beneficiarios/beneficiario_detail.html" %}
{% load static %}
{% block includes %}
    <link rel="stylesheet" href="{% static 'Beneficiarios/styles.css' %}">
    <link rel="stylesheet" href="{% static 'Formularios/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/datatables.min.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
{% endblock includes %}
{% block scripts %}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="{% static 'js/formularios.js' %}" ></script>
    <script>


        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });

        function deleteEvidence(ev){
            swal({
                title: "¿Estás seguro que quieres eliminar la evidencia?",
                text: "No es posible revertir esta acción.",
                icon: "warning",
                buttons: ['Cancelar', 'Confirmar'],
            })
                .then((willDelete) => {
                    if (willDelete) {
                        df = {
                            evi:ev
                        }
                        $.ajax({
                            url: '{% url 'Formularios:delete_evidencias' %}', // the endpoint
                            type: "POST", // http method
                            data: df, // data sent with the post request
                            // handle a successful response
                            success: function (json) {
                                var dt_table = $('#evidencias_table')
                                dt_table.DataTable().ajax.reload(null,false)
                            },
                            // handle a non-successful response
                            error: function (xhr, errmsg, err) {

                            }

                        });
                    } else {
                        return false;
                    }
                });

        }
        function downloadEvidence(ev){
            df = {
                evi:ev
            }
            $.ajax({
                url: '{% url 'Formularios:download_evidencias' %}', // the endpoint
                type: "GET", // http method
                data: df, // data sent with the post request
                // handle a successful response
                success: function (json) {
                    if(json['success'] == true){
                        window.open(json['url']);
                    }
                },
                error: function (xhr, errmsg, err) {
                    swal({
                        title: "Error al intentar Descargar",
                        text: "No es posible realizar esta acción. Compruebe su conexión a internet y vuelva a intentar.",
                        icon: "warning",
                        button: 'Cancelar',
                    })
                }
            });
        }



    </script>
    <script>
        $(document).ready(function() {

            var URL = '{% url 'Formularios:evidencias_json' beneficiario.id %}';
            var dt_table = $('#evidencias_table').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json",
                },
                order: [[ 1, "desc" ]],
                responsive: false,
                columnDefs: [
                    {
                        name: 'nombre',
                        orderable: true,
                        searchable: true,
                        targets: [0]
                    },
                    {
                        name: 'fecha_creacion',
                        orderable: true,
                        searchable: true,
                        targets: [1]
                    },
                    {
                        name: 'descripcion',
                        orderable: true,
                        searchable: true,
                        targets: [2]
                    },
                    {
                        name: 'acciones',
                        orderable: false,
                        searchable: false,
                        targets: [3]
                    },
                ],
                searching: true,
                processing: true,
                serverSide: true,
                stateSave: false,
                ajax: {
                    url: URL
                }
            });

        });
    </script>


{% endblock scripts %}

{% block antecedentes %}{% endblock antecedentes %}

{% block ir_evidencias %}
    <a href="{% url 'Beneficiarios:beneficiario' beneficiario.id %}" class="btn btn-outline-primary btn-sm">
        Ir a perfil
    </a>
{% endblock ir_evidencias %}

{% block beneficiario-content %}
    <br>
    <h2>Evidencias <div class="clearfix d-inline-block">
        <a href='{% url 'Formularios:evidencias_register' beneficiario.id %}'><i class="fas fa-plus-square icon-add"></i></a>
    </div></h2>
    <br><br>
    <table id="evidencias_table" class="datatable table table-hover table-striped">
        <thead>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Descripción</th>
        <th>Acciones</th>
        </thead>
        <tbody><form>{% csrf_token %}</form></tbody>
    </table>

{% endblock beneficiario-content %}

Formularios/templates/Formularios/nota_view.html
<!--
  NEF-47, NEF-48, NEF-49
-->
{% extends "Beneficiarios/beneficiario_detail.html" %}
{% load static %}
{% block includes %}
<link rel="stylesheet" href="{% static 'Formularios/styles.css' %}">
<link rel="stylesheet" href="{% static 'Beneficiarios/styles.css' %}">
{% endblock includes %}

{% block antecedentes %}{% endblock antecedentes %}

{% block beneficiario-content %}
<div class="container pt-4">
  <div class="card">
    <h5 class="card-header text-center">Nota del Nefrólogo</h5>
    <div class="card-body">
      <div class="container-fluid">
        <div class="row justify-content-end py-2">
          <div class="col-sm-3 text-right labelsFormulario">
            Fecha de nota:
          </div>
          <div class="col-sm-2 text-left">
            {{ nota.fecha_creacion }}
          </div>
        </div>
        <hr>
        <div class="row justify-content-center pb-3">
          <div class="col-8">
            <text class="labelsFormulario">Observaciones:</text>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-8">
            <textarea class="form-control cursorna" rows="10" disabled> {{ nota.nota }} </textarea>
          </div>
        </div>
        <br><br>
        <!--Botones-->
        {% if perms.Formularios.change_notas or perms.Formularios.delete_notas %}
        <div class="row justify-content-center pb-3">
          <div class="col-12">
            <div class="clearfix">
              <div class="float-right wrap">
                <div class=" pr-2">
                  {% if perms.Formularios.delete_notas %}
                  <form method="POST" action="{% url 'Formularios:delete_notas' nota.id %}" id="delete_form">
                    {% csrf_token %}
                    <button type="button" class="button btn btn-form">Borrar</button>
                  </form>
                  {% endif %}
                </div>
                {% if perms.Formularios.change_notas %}
                <a href="{% url 'admin:Formularios_notas_change' nota.id %}"><button type="button" class="button btn btn-edit">Editar</button></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock beneficiario-content %}

{% block scripts %}
<script src="{% static 'js/formularios.js' %}"></script>
{% endblock scripts %}